// default package
// Generated 29-Nov-2017 10:44:19 by Hibernate Tools 4.3.5.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private CartId id;

	public Cart() {
	}

	public Cart(CartId id) {
		this.id = id;
	}

	public CartId getId() {
		return this.id;
	}

	public void setId(CartId id) {
		this.id = id;
	}

}
