// default package
// Generated 29-Nov-2017 10:44:19 by Hibernate Tools 4.3.5.Final

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private ProductsId id;

	public Products() {
	}

	public Products(ProductsId id) {
		this.id = id;
	}

	public ProductsId getId() {
		return this.id;
	}

	public void setId(ProductsId id) {
		this.id = id;
	}

}
