// default package
// Generated 29-Nov-2017 10:44:19 by Hibernate Tools 4.3.5.Final

/**
 * UserdetailsId generated by hbm2java
 */
public class UserdetailsId implements java.io.Serializable {

	private String uname;
	private String pass;

	public UserdetailsId() {
	}

	public UserdetailsId(String uname, String pass) {
		this.uname = uname;
		this.pass = pass;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserdetailsId))
			return false;
		UserdetailsId castOther = (UserdetailsId) other;

		return ((this.getUname() == castOther.getUname()) || (this.getUname() != null && castOther.getUname() != null
				&& this.getUname().equals(castOther.getUname())))
				&& ((this.getPass() == castOther.getPass()) || (this.getPass() != null && castOther.getPass() != null
						&& this.getPass().equals(castOther.getPass())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUname() == null ? 0 : this.getUname().hashCode());
		result = 37 * result + (getPass() == null ? 0 : this.getPass().hashCode());
		return result;
	}

}
