// default package
// Generated 29-Nov-2017 10:44:19 by Hibernate Tools 4.3.5.Final

/**
 * Userdetails generated by hbm2java
 */
public class Userdetails implements java.io.Serializable {

	private UserdetailsId id;

	public Userdetails() {
	}

	public Userdetails(UserdetailsId id) {
		this.id = id;
	}

	public UserdetailsId getId() {
		return this.id;
	}

	public void setId(UserdetailsId id) {
		this.id = id;
	}

}
